import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const avenirNext = localFont({
  src: [
    {
      path: "./fonts/AvenirNext-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/AvenirNext-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/AvenirNext-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/AvenirNext-MediumItalic.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/AvenirNext-DemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/AvenirNext-DemiBoldItalic.woff2",
      weight: "600",
      style: "italic",
    },
    {
      path: "./fonts/AvenirNext-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/AvenirNext-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/AvenirNext-Heavy.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/AvenirNext-HeavyItalic.woff2",
      weight: "800",
      style: "italic",
    },
    {
      path: "./fonts/AvenirNext-UltraLight.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/AvenirNext-UltraLightItalic.woff2",
      weight: "100",
      style: "italic",
    },
  ],
  variable: "--font-sans",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${avenirNext.variable} min-h-full antialiased`}>
      <body>{children}</body>
    </html>
  );
}
